# Generated by Django 4.2.10 on 2024-03-27 09:07

import apps.common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('institution_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=32, verbose_name='Institution type')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('intake_months', apps.common.models.ModifiedArrayField(base_field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=32), blank=True, null=True, size=None, verbose_name='Intake month')),
                ('tuition_fee', models.CharField(blank=True, help_text='yearly tuition fee', max_length=255, null=True, verbose_name='Tuition fee')),
                ('application_fee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Application fee')),
                ('living_cost', models.CharField(blank=True, help_text='monthly living cost', max_length=255, null=True, verbose_name='Living cost')),
                ('visa_fee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Visa fee')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='common.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='UniversityCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('qualification_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('master', 'Master'), ('doctorate', 'Doctorate')], max_length=32, verbose_name='Qualification level')),
                ('duration', models.PositiveIntegerField(help_text='In years', verbose_name='Duration')),
                ('study_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('distance', 'Distance')], max_length=32, verbose_name='Study type')),
                ('tuition_fee', models.DecimalField(decimal_places=2, help_text='In USD', max_digits=10, verbose_name='Tuition fee')),
                ('intake_months', apps.common.models.ModifiedArrayField(base_field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=32), blank=True, null=True, size=None, verbose_name='Intake month')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='universities.specialty', verbose_name='Specialty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'University course',
                'verbose_name_plural': 'University courses',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('document_type', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL')], max_length=32, verbose_name='Document type')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Required document',
                'verbose_name_plural': 'Required documents',
            },
        ),
    ]
