# Generated by Django 4.2.10 on 2024-03-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_specialty_name_en_specialty_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='establishment_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Establishment year'),
        ),
        migrations.AddField(
            model_name='university',
            name='has_dormitory',
            field=models.BooleanField(default=False, verbose_name='Has dormitory'),
        ),
        migrations.AddField(
            model_name='university',
            name='students_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Students count'),
        ),
    ]
