# Generated by Django 4.2.10 on 2024-03-28 11:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About'),
        ),
    ]
