# Generated by Django 4.2.10 on 2024-03-29 12:27

import apps.common.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_university_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='universities/images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='universities/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='university',
            name='intake_months',
            field=apps.common.models.ModifiedArrayField(base_field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=32), blank=True, null=True, size=None, verbose_name='Intake months'),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='intake_months',
            field=apps.common.models.ModifiedArrayField(base_field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=32), blank=True, null=True, size=None, verbose_name='Intake months'),
        ),
    ]
