# Generated by Django 4.2.10 on 2024-03-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_establishment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='students_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Students count'),
        ),
    ]
