# Generated by Django 4.2.10 on 2024-03-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_image_university_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='university',
            name='full_scolarship',
            field=models.BooleanField(default=False, verbose_name='Full scolarship'),
        ),
        migrations.AddField(
            model_name='university',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is featured'),
        ),
    ]
