# Generated by Django 4.2.10 on 2024-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_university_students_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourse',
            name='qualification_level',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('certificate', 'Certificate'), ('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('master', 'Master'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=32, verbose_name='Qualification level'),
        ),
    ]
