# Generated by Django 4.2.10 on 2024-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_universitycourse_qualification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourse',
            name='duration',
            field=models.DecimalField(decimal_places=1, help_text='In years', max_digits=3, verbose_name='Duration'),
        ),
    ]
