# Generated by Django 4.2.10 on 2025-04-04 17:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_alter_universitycourse_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='free_consultation',
            field=models.BooleanField(default=False, verbose_name='Free consultation'),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Scholarship description'),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='tuition_fee_currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('kgs', 'KGS'), ('kzt', 'KZT'), ('usd', 'USD'), ('eur', 'EUR'), ('rub', 'RUB'), ('krw', 'KRW'), ('jpy', 'JPY')], default='usd', max_length=32, verbose_name='Tuition fee currency'),
        ),
        migrations.AlterField(
            model_name='university',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='university',
            name='about_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='university',
            name='about_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='university',
            name='about_uz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='university',
            name='full_scolarship',
            field=models.BooleanField(default=False, verbose_name='Full scholarship'),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='qualification_level',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('course', 'Course'), ('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('master', 'Master'), ('phd', 'PhD')], max_length=32, verbose_name='Qualification level'),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, help_text='currency is selected below', max_digits=10, verbose_name='Tuition fee'),
        ),
        migrations.CreateModel(
            name='CourseAdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('requirement', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL')], max_length=255, verbose_name='Requirement')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('university_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirements', to='universities.universitycourse', verbose_name='University course')),
            ],
            options={
                'verbose_name': 'Course admission requirement',
                'verbose_name_plural': 'Course admission requirements',
            },
        ),
    ]
