# Generated by Django 4.2.10 on 2024-03-29 16:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_alter_university_image_alter_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='university',
            name='about_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='university',
            name='about_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='university',
            name='about_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='university',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='university',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='university',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
