# Generated by Django 4.2.10 on 2025-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_university_free_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourse',
            name='tuition_fee_currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('kgs', 'KGS'), ('kzt', 'KZT'), ('usd', 'USD'), ('eur', 'EUR'), ('rub', 'RUB'), ('krw', 'KRW'), ('jpy', 'JPY'), ('cad', 'CAD'), ('gbp', 'GBP'), ('myr', 'MYR'), ('aud', 'AUD'), ('cny', 'CNY'), ('sar', 'SAR'), ('aed', 'AED')], default='usd', max_length=32, verbose_name='Tuition fee currency'),
        ),
    ]
