# Generated by Django 4.2.10 on 2025-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_alter_universitycourse_tuition_fee_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='more_courses',
            field=models.URLField(blank=True, null=True, verbose_name='More Courses'),
        ),
    ]
