# Generated by Django 4.2.10 on 2024-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_en',
            field=models.CharField(max_length=1024, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_ru',
            field=models.CharField(max_length=1024, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_uz',
            field=models.CharField(max_length=1024, null=True, verbose_name='Text'),
        ),
    ]
