# Generated by Django 4.2.10 on 2024-04-13 16:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_university', ckeditor.fields.RichTextField(verbose_name='Find the right university')),
                ('find_university_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Find the right university')),
                ('find_university_en', ckeditor.fields.RichTextField(null=True, verbose_name='Find the right university')),
                ('find_university_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Find the right university')),
                ('our_services', ckeditor.fields.RichTextField(verbose_name='Our services')),
                ('our_services_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Our services')),
                ('our_services_en', ckeditor.fields.RichTextField(null=True, verbose_name='Our services')),
                ('our_services_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Our services')),
                ('card_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Card title')),
                ('card_title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Card title')),
                ('card_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Card title')),
                ('card_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Card title')),
                ('card_body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Card body')),
                ('card_body_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Card body')),
                ('card_body_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Card body')),
                ('card_body_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Card body')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', ckeditor.fields.RichTextField(verbose_name='Privacy policy')),
                ('policy_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Privacy policy')),
                ('policy_en', ckeditor.fields.RichTextField(null=True, verbose_name='Privacy policy')),
                ('policy_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Privacy policy')),
            ],
            options={
                'verbose_name': 'Privacy policy',
                'verbose_name_plural': 'Privacy policy',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField(verbose_name='Terms and conditions')),
                ('terms_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Terms and conditions')),
                ('terms_en', ckeditor.fields.RichTextField(null=True, verbose_name='Terms and conditions')),
                ('terms_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Terms and conditions')),
            ],
            options={
                'verbose_name': 'Terms and conditions',
                'verbose_name_plural': 'Terms and conditions',
            },
        ),
    ]
