# Generated by Django 4.2.10 on 2025-04-04 17:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='card_body',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Card body'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='card_body_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Card body'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='card_body_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Card body'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='card_body_uz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Card body'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='find_university',
            field=tinymce.models.HTMLField(verbose_name='Find the right university'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='find_university_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Find the right university'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='find_university_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Find the right university'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='find_university_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Find the right university'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_services',
            field=tinymce.models.HTMLField(verbose_name='Our services'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_services_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Our services'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_services_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Our services'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_services_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Our services'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='policy',
            field=tinymce.models.HTMLField(verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='policy_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='policy_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='policy_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms',
            field=tinymce.models.HTMLField(verbose_name='Terms and conditions'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Terms and conditions'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Terms and conditions'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Terms and conditions'),
        ),
    ]
