# Generated by Django 4.2.10 on 2024-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_agency_user_telegram_id_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Phone Number'),
        ),
    ]
