# Generated by Django 4.2.10 on 2024-04-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_agency_address_agency_document_agency_email_and_more'),
        ('users', '0005_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.agency', verbose_name='Agency'),
        ),
    ]
