# Generated by Django 4.2.10 on 2024-07-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwayadvice',
            name='icon',
            field=models.FileField(null=True, upload_to='articles/pathway-advices/icons/', verbose_name='Icon'),
        ),
    ]
