# Generated by Django 4.2.10 on 2024-03-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=15, verbose_name='Status'),
        ),
    ]
