# Generated by Django 4.2.10 on 2024-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sent_telegram',
            field=models.BooleanField(default=False, verbose_name='Sent Telegram'),
        ),
    ]
