# Generated by Django 4.2.10 on 2024-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_advisorapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorapplication',
            name='who_are_you',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=31, null=True, verbose_name='Who Are You'),
        ),
    ]
