# Generated by Django 4.2.10 on 2024-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_advisorapplication_who_are_you'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisorapplication',
            options={'verbose_name': 'Request for Advise', 'verbose_name_plural': 'Requests for Advise'},
        ),
        migrations.AlterField(
            model_name='advisorapplication',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('TALKED', 'Talked'), ('NOT_INTERESTED', 'Not Interested')], default='NEW', max_length=15, verbose_name='Status'),
        ),
    ]
