# Generated by Django 4.2.10 on 2024-07-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitesettings'),
        ('applications', '0009_advisorapplication_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorapplication',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.region', verbose_name='Region'),
        ),
    ]
