# Generated by Django 4.2.10 on 2025-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_university_more_courses'),
        ('applications', '0011_contactusapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorapplication',
            name='matched_universities',
            field=models.ManyToManyField(blank=True, to='universities.university', verbose_name='Matched Universities'),
        ),
    ]
