# Generated by Django 4.2.10 on 2025-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_advisorapplication_matched_universities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorapplication',
            name='current_education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', 'Bachelor')], max_length=31, null=True, verbose_name='Current Education Level'),
        ),
        migrations.AlterField(
            model_name='advisorapplication',
            name='needed_education_level',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master')], max_length=31, null=True, verbose_name='Needed Education Level'),
        ),
        migrations.AlterField(
            model_name='advisorapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('talked', 'Talked'), ('not_interested', 'Not Interested')], default='new', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='advisorapplication',
            name='type',
            field=models.CharField(choices=[('eligibility_check', 'Eligibility Check'), ('speak_with_advisor', 'Speak with Advisor')], max_length=31, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='advisorapplication',
            name='who_are_you',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent')], max_length=31, null=True, verbose_name='Who Are You'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='received', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactusapplication',
            name='inquiry_type',
            field=models.CharField(choices=[('need_help', 'Need Help'), ('complaint', 'Complaint')], max_length=31, verbose_name='Inquiry Type'),
        ),
    ]
