# Generated by Django 4.2.10 on 2025-04-04 17:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_agency_address_agency_document_agency_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About'),
        ),
    ]
